DEF BATTLETOWER_PARTY_LENGTH EQU 3 ; previous-trainer species tracking only
DEF BATTLETOWER_STREAK_LENGTH EQU 4

DEF BATTLETOWER_NUM_UNIQUE_MON EQU 40 ; DevNote - Battle Tower - lvl 100 has 80 unique mon, others have 40
DEF BATTLETOWER_NUM_UNIQUE_TRAINERS EQU 70

DEF BATTLETOWER_MON_STRUCT_LENGTH EQU 1 + 1 + NUM_MOVES ; species, item, moves
DEF BATTLETOWER_CHALLENGE_POOL_ENTRY_LENGTH EQU 1 + 2 + 1 ; bank, address, count
DEF BATTLETOWER_ENEMY_PARTY_LENGTH EQU 6
DEF BATTLETOWER_CHALLENGE_LEVEL_STEP EQU 20
DEF BATTLETOWER_MIN_CHALLENGE_LEVEL EQU 20
DEF BATTLETOWER_MAX_CHALLENGE_LEVEL EQU 100

DEF BATTLETOWER_TRAINERDATALENGTH EQU 18 * 2 ; $24
;BATTLE_TOWER_STRUCT_LENGTH EQU NAME_LENGTH + BATTLETOWER_PARTY_LENGTH * NICKNAMED_MON_STRUCT_LENGTH + BATTLETOWER_TRAINERDATALENGTH ; $e0
DEF BATTLE_TOWER_STRUCT_LENGTH EQU NAME_LENGTH + BATTLETOWER_ENEMY_PARTY_LENGTH * NICKNAMED_MON_STRUCT_LENGTH + BATTLETOWER_TRAINERDATALENGTH ; $191

; Battle Tower save-file flag bits in sBattleTowerSaveFileFlags
DEF BATTLETOWER_SAVEFILEFLAG_SAVEFILE_IS_YOURS_F EQU 0
DEF BATTLETOWER_SAVEFILEFLAG_EXPLANATION_READ_F EQU 1
DEF BATTLETOWER_SAVEFILEFLAG_SCALE_PARTY_F EQU 2
DEF BATTLETOWER_SAVEFILEFLAG_RANDOM_MIRROR_F EQU 3

DEF BATTLETOWER_SAVEFILEFLAG_SAVEFILE_IS_YOURS EQU 1 << BATTLETOWER_SAVEFILEFLAG_SAVEFILE_IS_YOURS_F
DEF BATTLETOWER_SAVEFILEFLAG_EXPLANATION_READ EQU 1 << BATTLETOWER_SAVEFILEFLAG_EXPLANATION_READ_F
DEF BATTLETOWER_SAVEFILEFLAG_SCALE_PARTY EQU 1 << BATTLETOWER_SAVEFILEFLAG_SCALE_PARTY_F
DEF BATTLETOWER_SAVEFILEFLAG_RANDOM_MIRROR EQU 1 << BATTLETOWER_SAVEFILEFLAG_RANDOM_MIRROR_F

; Battle Tower mirror mode values for wHandOfGod / future persisted mode glue
DEF BATTLETOWER_MIRROR_NONE EQU 0
DEF BATTLETOWER_MIRROR_EXACT_COPY EQU 1
DEF BATTLETOWER_MIRROR_RANDOM_TEAM EQU 2

; Battle Tower compact pool indexes
	const_def
	const BATTLETOWER_POOL_EARLY_EVOLVED
	const BATTLETOWER_POOL_EVOLVED
	const BATTLETOWER_POOL_PSEUDO_LEGENDARY
	const BATTLETOWER_POOL_LEGENDARY
	const BATTLETOWER_POOL_UBER
DEF NUM_BATTLETOWER_POOLS EQU const_value

; wBTChoiceOfLvlGroup values
	const_def 1
	const BATTLETOWER_CHALLENGE_NOVICE
	const BATTLETOWER_CHALLENGE_LEADER
	const BATTLETOWER_CHALLENGE_ELITE
	const BATTLETOWER_CHALLENGE_CHAMP
	const BATTLETOWER_CHALLENGE_MASTER
DEF NUM_BATTLETOWER_CHALLENGES EQU const_value - 1

; BattleTowerAction setval arguments (see engine/events/battle_tower/battle_tower.asm)
	const_def
	const BATTLETOWERACTION_CHECK_EXPLANATION_READ
	const BATTLETOWERACTION_SET_EXPLANATION_READ
	const BATTLETOWERACTION_GET_CHALLENGE_STATE
	const BATTLETOWERACTION_SAVE_AND_QUIT
	const BATTLETOWERACTION_CHALLENGECANCELED
	const BATTLETOWERACTION_05
	const BATTLETOWERACTION_06 ; reset stuff in SRAM bank 5
	const BATTLETOWERACTION_SAVELEVELGROUP
	const BATTLETOWERACTION_LOADLEVELGROUP
	const BATTLETOWERACTION_CHECKSAVEFILEISYOURS
	const BATTLETOWERACTION_0A
	const BATTLETOWERACTION_GSBALL
	const BATTLETOWERACTION_0C ; more time stuff in SRAM bank 5
	const BATTLETOWERACTION_0D ; more time stuff in SRAM bank 5
	const BATTLETOWERACTION_EGGTICKET
	const BATTLETOWERACTION_0F ; check w3_d090
	const BATTLETOWERACTION_10 ; dw based on s5_a800
	const BATTLETOWERACTION_11 ; store 0 in s5_aa8d
	const BATTLETOWERACTION_12 ; store 1 in s5_aa8d
	const BATTLETOWERACTION_13 ; check s5_aa8d
	const BATTLETOWERACTION_14 ; check BATTLETOWER_SAVEFILEFLAG_SAVEFILE_IS_YOURS
	const BATTLETOWERACTION_15 ; set BATTLETOWER_SAVEFILEFLAG_SAVEFILE_IS_YOURS
	const BATTLETOWERACTION_16 ; update time in SRAM bank 5
	const BATTLETOWERACTION_17 ; check time in SRAM bank 5
	const BATTLETOWERACTION_LEVEL_CHECK
	const BATTLETOWERACTION_UBERS_CHECK
	const BATTLETOWERACTION_RESETDATA ; clear data
	const BATTLETOWERACTION_GIVEREWARD ; give reward
	const BATTLETOWERACTION_1C ; set won challenge
	const BATTLETOWERACTION_1D ; set received reward
	const BATTLETOWERACTION_CHOOSEREWARD ; save options
	const BATTLETOWERACTION_SAVEOPTIONS
	const BATTLETOWERACTION_SET_SCALE_PARTY
	const BATTLETOWERACTION_CLEAR_SCALE_PARTY
	const BATTLETOWERACTION_CHECK_SCALE_PARTY
	const BATTLETOWERACTION_SET_RANDOM_MIRROR
	const BATTLETOWERACTION_CLEAR_RANDOM_MIRROR
	const BATTLETOWERACTION_CHECK_RANDOM_MIRROR
	const BATTLETOWERACTION_CLEAR_MODE_OPTIONS
	const BATTLETOWERACTION_SELECT_RANDOM_MIRROR_MODE
	const BATTLETOWERACTION_LOAD_MIRROR_MODE

; BattleTowerAction return values
; - from BATTLETOWERACTION_GSBALL
DEF GS_BALL_AVAILABLE EQU $b

; BattleTowerText arguments (see engine/events/battle_tower/trainer_text.asm)
	const_def 1
	const BATTLETOWERTEXT_INTRO
	const BATTLETOWERTEXT_WIN_TEXT
	const BATTLETOWERTEXT_LOSS_TEXT

; sBattleTowerChallengeState values
	const_def
	const BATTLETOWER_NO_CHALLENGE
	const BATTLETOWER_SAVED_AND_LEFT
	const BATTLETOWER_CHALLENGE_IN_PROGRESS
	const BATTLETOWER_WON_CHALLENGE
	const BATTLETOWER_RECEIVED_REWARD
