Text_BattleTowerIntroduction_2::
	text "Battle Tower is"
	line "the most popular"
	cont "extreme #mon"
	cont "challenge."
	para "There are five"
	line "challenge levels"
	cont "with the top two"
	cont "available to"
	cont "Champion level"
	cont "trainers."
	para "First choose a"
	line "challenge level."
	para "Higher challenge"
	line "levels contain"
	cont "more powerful and"
	cont "rare #mon."
	para "Then choose four"
	line "6v6 battles or"
	cont "seven 3v3 battles."
	para "Then choose if you"
	line "want to use your"
	cont "current party or a"
	cont "random party."
	para "If you choose your"
	line "current party you"
	cont "can also choose to"
	cont "scale your party"
	cont "to the challenge"
	cont "level."
	done

Text_BattleTowerRules::
	text "First choose a"
	line "challenge level."
	para "Higher challenge"
	line "levels contain"
	cont "more powerful and"
	cont "rare #mon."

	para "Then choose four"
	line "6v6 battles or"
	cont "seven 3v3 battles."

	para "Then choose if you"
	line "want to use your"
	cont "current party or a"
	cont "random party."

	para "If you choose your"
	line "current party you"
	cont "can also choose to"
	cont "scale your party"
	cont "to the challenge"
	cont "level."

	para "Different prizes"
	line "are won in each."
	done
